---
title: "Creating Fake Data Sets To Explore Hypotheses"
author: "Anoob Prakash"
date: "10 October 2018"
output: html_document
---

```{r}


n <- 30 # sample size
height <- runif(n, min = 0.2, max = 1.3) # height increment (dependent)
WUE <- runif(n, min = -0.01, max = 0.99) # wateruse efficiency (dependent)
temp <- runif(n, min = 4, max = 26) # temperature in degree celsius (independent)
temp1 <- rep(c("hot","cold"), 15)
ID <- seq_len(n)
expData <- data.frame(ID,temp,height,WUE)
head(expData)

# Regresion analysis between temperature and WUE
expModel <- lm(WUE~temp, data = expData)
print(expModel)
summary(expModel)

library(ggplot2)
expPlot <- ggplot(data = expData,
                    aes(x=WUE, y=temp)) + 
                    geom_point() +
                    stat_smooth(method=lm, se = 0.99)
print(expPlot)

# ANOVA for the same dataset with the temperature variable as either "Hot" or "Cold"
temp1 <- rep(c("hot","cold"), 15)
anoData <- data.frame(ID, temp1, WUE)
str(anoData)
head(anoData)
summary(anoData)

# ANOVA model
anoModel <- aov(WUE~temp1,data = anoData)
print(anoModel)
print(summary(anoModel))
summary(anoModel)


# Basic ggplot of ANOVA data
anoPlot <- ggplot(data=anoData,
                  aes(x=temp1,y=WUE,
                      fill=temp1)) +
  geom_boxplot() # fill gives color to the plots as well as give legend for the same
print(anoPlot)

```

### Reducing the range of temperature variable

```{r}


n <- 30 
height <- runif(n, min = 0.2, max = 1.3) 
WUE <- runif(n, min = -0.01, max = 0.99) 
temp <- runif(n, min = 18, max = 22) # temperature range reduced 
ID <- seq_len(n)
expData <- data.frame(ID,temp,height,WUE)
head(expData)

# Regresion analysis between temperature and WUE
expModel <- lm(WUE~temp, data = expData)
print(expModel)
summary(expModel)

library(ggplot2)
expPlot <- ggplot(data = expData,
                    aes(x=WUE, y=temp)) + 
                    geom_point() +
                    stat_smooth(method=lm, se = 0.99)
print(expPlot)
```

### Reducing the range of WUE variable

```{r}


n <- 30 
height <- runif(n, min = 0.2, max = 1.3) 
WUE <- runif(n, min = -0.30, max = 0.80) # range reduced
temp <- runif(n, min = 18, max = 22)  # range reduced
ID <- seq_len(n)
expData <- data.frame(ID,temp,height,WUE)
head(expData)

# Regresion analysis between temperature and WUE
expModel <- lm(WUE~temp, data = expData)
print(expModel)
summary(expModel)

library(ggplot2)
expPlot <- ggplot(data = expData,
                    aes(x=WUE, y=temp)) + 
                    geom_point() +
                    stat_smooth(method=lm, se = 0.99)
print(expPlot)
```

### Increasing the sample size

```{r}


n <- 1000 # sample size increased 
height <- runif(n, min = 0.2, max = 1.3) 
WUE <- runif(n, min = -0.30, max = 0.80) # range reduced
temp <- runif(n, min = 18, max = 22)  # range reduced
ID <- seq_len(n)
expData <- data.frame(ID,temp,height,WUE)
head(expData)

# Regresion analysis between temperature and WUE
expModel <- lm(WUE~temp, data = expData)
print(expModel)
summary(expModel)

library(ggplot2)
expPlot <- ggplot(data = expData,
                    aes(x=WUE, y=temp)) + 
                    geom_point() +
                    stat_smooth(method=lm, se = 0.99)
print(expPlot)
```

### Fixing the mean and standard deviation to a specific range

##### Replacing runif() with rnorm() for data generation

```{r}


n <- 100 
height <- rnorm(n, mean = 0.5, sd = 0.25) 
WUE <- rnorm(n, mean=0.45,sd=0.20)
temp <- rnorm(n, mean=15,sd=0.10) 
ID <- seq_len(n)
expData <- data.frame(ID,temp,height,WUE)
head(expData)

# Regresion analysis between temperature and WUE
expModel <- lm(WUE~temp, data = expData)
print(expModel)
summary(expModel)

library(ggplot2)
expPlot <- ggplot(data = expData,
                    aes(x=WUE, y=temp)) + 
                    geom_point() +
                    stat_smooth(method=lm, se = 0.99)
print(expPlot)
```