---
title: "Learning with Curiosity"
author: "Anoob Prakash"
output: 
  html_document: 
    theme: cosmo
---
***
#### _I have not failed. I've just found 10,000 ways that won't work._ - Edison
***
>Assignments and Projects

* Homework 1  
 Learning about GitHub and setting up website for uploading lab assignments. 

* [Homework 2](homework2.html)  
Working with different diagrams to illustrate and draw out an outline for potential research areas.
 
* [Homework 3](NotesBeamer.pdf)  
Learning to use beamer and creating ones own presentation using beamer and R markdown.  

* [Homework 4](Homework4RegularExpressions.html)  
Doing some basic coding assignments and learning  to use regular expressions in a text editor.

* [Homework 5](Homework5dplyr.html)  
Learning to code in dplyr and how to use piping for efficient coding.

* [Homework 6](Homework6DataDistribution.html)  
Simulating and fitting data distributions.

* [Homework 7](Homework7CFakedata.html)  
Creating Fake Data Sets To Explore Hypotheses.

* [Homework 8](Homework8StructuredProgramming.html)   
Creating functions and working with structured programming.  

* [Homework 9-10](Homework10Looping.html)   
Performing `for` loops and randomisation of data.  

* [Homework 11](Homework11ggplot.html)   
Understanding the various options available for plotting when using `ggplot2`. 

* [Leaflet for R](leafletR.html)   
Creating interactive maps easily within R. 

***
#####Course instructors: [Nicholas J. Gotelli](https://gotellilab.github.io/Bio381/) & [Lauren Ash](https://lvash.github.io/Bio381_2018/#id-section1)

Github profile: [anoobvinu07](https://github.com/anoobvinu07)   

prettydoc : [Create pretty documents from R markdown](http://yixuan.cos.name/prettydoc/themes.html)


